name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 95.181.224.33
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "== Deploy started =="

          cd /var/telegram/front-apps/apps/joint-purchases

          echo "== Pulling latest changes =="
          git reset --hard
          git clean -fd
          git pull origin main

          echo "== Rebuilding containers =="
          docker rm -f join-purchases || true
          docker-compose down --remove-orphans
          docker-compose up --build -d

          echo "== Deploy finished ✅ =="
